// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deleteposts.sql

package database

import (
	"context"
)

const deletePosts = `-- name: DeletePosts :exec
DELETE FROM posts
`

func (q *Queries) DeletePosts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deletePosts)
	return err
}
